<div class="topRegion">Updated: March 2012</div>

<!-- Page section: pgHeading -->
<div class="pgHeading">
	<h1>Privacy Policy</h1>
</div>

<p>This privacy policy covers the web site <a href="http://nalliTrack.com" target="_blank">NalliTrack.com</a> (the "<span style="text-decoration: underline;">Site</span>") and the services available through the site. </p>
<h2>1. Information Collection</h2>
<h6>Information You Provide</h6>
<p>If you register for a free account, we collect your email address and password and may collect certain demographic information, such as your time zone, city, state or country. You may also visit our site anonymously.</p>
<p>If you purchase a premium level account, you must provide certain additional personally identifiable information on our order form; in particular, certain contact information (including your name, address, email address, and billing address). However we do not collect or store any financial information (including credit card number and expiration date). We use a <a href="https://cms.paypal.com/cgi-bin/marketingweb?cmd=_render-content&content_ID=ua/Privacy_full&locale.x=en_US" >third-party service</a> for all billing services and transactions.</p>
<p>If you submit a testimonial to the Site, we may collect your name, email address and any other personally identifiable information that you voluntarily include in your testimonial.</p>
<p>From time-to-time we may provide you with the opportunity to participate in our surveys on the Site. If you participate, we may request certain personally identifiable information from you. Participation in these surveys is completely voluntary and you therefore have a choice whether or not to disclose this information. The requested information typically includes demographic information (such as zip code), and could also include contact information (such as your name and address).</p>
<h6>Automatically Collected Information</h6>
<p>As is true of most Web sites, we gather certain information automatically and store it in log files. This information includes internet protocol (IP) addresses, browser type, internet service provider (ISP), referring/exit pages, operating system, date/time stamp, and clickstream data. We use this information to analyze trends, to administer the Site, to understand users' movements around the Site and to gather demographic information about our user base as a whole.</p>
<p>We also use "cookies" to recognize specific visitors and more quickly provide personalized content, or grant you unimpeded access to the Site. Cookies are small text files a Web site can use to recognize repeat users. With cookies enabled, you will often not need to fill in password or contact information. Information gathered through cookies also helps us measure use of our Site. Cookie data allow us to track usage behavior and compile data that we can use to improve the Site.</p>
<p>Generally, cookies work by assigning a unique number to the user that has no meaning outside of the Web site that he or she is visiting. You can easily turn off cookies. Most browsers have a feature that allows the user to refuse cookies or issues a warning when cookies are being sent. Please consult the "Help" section of your browser for more information about how to disable cookies. However, our Site will not function as effectively without cookies. Enabling cookies ensures a smooth, efficient visit to our Site.</p>
<p>We use a third-party tracking service that uses cookies and web beacons to track aggregated anonymized data about visitors to capture usage and volume statistics. We have no access or control over these tracking technologies. This privacy policy covers the use of tracking technologies by NalliTrack only and does not cover the use of tracking technologies by any third party.</p>
<h6>Children Under Thirteen</h6>
<p>Our Site is not intended for, and is not directed to, children under the age of thirteen. </p>
<h2>2. Information Use</h2>
<p>In addition to the uses of your information described elsewhere in this privacy policy, we may also use your information in one or more of the following ways. We will not use or share your personally identifiable information in ways unrelated to those described in this privacy policy without your permission.</p>
<h6>Communications from NalliTrack</h6>
<p>We will use your information to communicate with you and provide you with transactional messages in response to your inquiries, to provide the services you request, and to manage your account. For example, when you register for an account (including a free account), you will receive a short welcome email.</p>
<p>We will send you service-related announcements when it is necessary to do so. For instance, if our service is temporarily suspended for maintenance, we might send you an email. If you are a paid subscriber, you may also receive emails regarding your account status and billing. Generally, you may not opt-out of these transactional communications which are not promotional in nature. If you do not wish to receive them, you have the option to deactivate your account.</p>
<p>We may use your information to contact you about other products or services that we offer and about products and services of third parties in which you may be interested. You may opt out of receiving such communications from us at any time (but not the transactional emails described in the paragraphs above) by contacting us as set out below in the section below entitled "Opting Out of Communications from NalliTrack".</p>
<p>We may post testimonials on the Site that user's submit to us. Submission of a testimonial is implied consent to post it on the Site. We will not include any personal identifiable information such as your first and last name. However, we may include vauge information like  first name and last initial (ie: John B).</p>
<h6>Use of Survey Questions and Results</h6>
<p><strong>Your survey questions, responses and results are kept in strict confidence and used in compliance with legal requirements. </strong>We will never use your survey questions or responses other than in accordance with this privacy policy unless we have your consent, and then only anonymously and by aggregating them with questions and responses from other surveys. You may be asked whether you wish to opt in to allowing us to use your survey questions and/or responses in this way at the time of creating your account or your survey. If you opt in, we may use the anonymized and aggregated survey questions and/or responses to create data services or content.</p>
<p>You have the ability to export, share, or publish data from your surveys. We provide various features to export, share, or publish your survey questions, responses, and results in summary or detailed format.</p>
<p>We may also use your information, including your survey questions and your respondent's responses, as well as aggregated data we collect through survey results to help you with your own survey creation and analysis, and to help us provide and improve our overall survey services.</p>
<h6>Statistical Analyses</h6>
<p>NalliTrack reserves the right to perform statistical analyses of user behavior and characteristics. We do this in order to measure interest in, and use of, the various areas of the Site. Statistical analyses are performed on anonymized, aggregated data.</p>
<h6>IP Addresses</h6>
<p>NalliTrack collects IP addresses for system administration and record keeping. Your IP address is automatically assigned to your computer when you use the World Wide Web. Our servers record incoming IP addresses. By tracking IP addresses, we can determine which Web sites refer the most people to NalliTrack. The IP addresses are analyzed in the aggregate, and we may also associate your IP address with your account for the purpose of managing your account and your surveys.</p>
<p>NalliTrack also collects the IP addresses of survey respondents on behalf of survey creators unless the survey creator has elected to create a survey without IP address collection turned on.</p>
<h2>3. Sharing Information with Third Parties</h2>
<h6>Service Providers</h6>
<p>We use third parties to provide billing services on our Site. When you purchase a service from us, we will share contact and credit card information as necessary for the billing service provider to provide that service. 		<br /> We may also from time to time share your personally identifiable information with other service providers to enable them to assist us to provide our survey-related services. Our service providers are contractually prohibited from using your information for any other purpose, including their own marketing purposes.</p>
<h6>Other Third Parties</h6>
<p><strong>NalliTrack does not ever disclose your survey questions or responses unless you permit or request for us to do so.</strong></p>
<p>NalliTrack may disclose survey questions and responses anonymously and by aggregating them with other users' survey questions and responses on an opt-in basis.</p>
<p>We may from time to time request your permission to provide your personally identifiable information to third parties for various purposes, including to allow those third parties to contact you about products and services in which you may be interested. If you permit us to do so (by opting-in), we may provide your information to those third parties for those purposes. If you later wish to opt out, you may do so at no cost by contacting us at <a href="mailto:support@NalliTrack.com">support@NalliTrack.com</a>. However, if you wish to stop receiving communications from a third party to which we provided your information prior to your opting out, you will need to contact that third party directly. We will not sell, rent, or otherwise provide your information to any other third parties, except as otherwise described in this privacy policy.</p>
<h2>4. Disclosures Required by Law</h2>
<p>We reserve the right to disclose your personally identifiable information as required by law and when we believe that disclosure is necessary to protect our rights and/or to comply with a judicial proceeding, court order, or legal process served on us.</p>
<h2>5. Merger or Other Acquisition</h2>
<p>We may transfer your personally identifiable information to a successor entity upon a merger, consolidation or other corporate reorganization in which NalliTrack participates or to a purchaser of all or substantially all of NalliTrack's assets to which this Site relates.</p>
<h2>7. Accessing, Changing or Deleting your Information</h2>
<p>We endeavor to ensure that your personally identifiable information is accurate by collecting it directly from you and providing you with the ability to update it. If your personally identifiable information changes, or if you no longer desire our service, you may correct, update, or delete your personally identifiable information or deactivate your account through the Site.</p>
<h2>9. Changes to this Privacy Policy</h2>
<p>We reserve the right to modify this privacy policy at any time, so please check for change notices on a regular basis. If we decide to change our privacy policy in a material way, we will post a prominent change notice on the Site, and we may notify you by email of those changes so that you continue to be aware of what information we collect, how we use it, and under what circumstances, if any, we disclose it.</p>
<h2>10. Links to Other Web Sites</h2>
<p>This may Site contains links to other Web sites that are not owned or controlled by NalliTrack. Please be aware that NalliTrack is not responsible for the privacy practices of such other Web sites. We encourage you to be aware when you leave our Site and to read the privacy policies of each and every Web site that collects personally identifiable information. This privacy policy applies only to information collected by this Site and the services available through the Site.</p>
<h2>Contact Us</h2>
<p>If you have any questions or suggestions regarding our privacy policy, please contact us at: info@NalliTrack.com</p>
