<div class="topRegion">Updated: August 2011</div>

<!-- Page section: pgHeading -->
<div class="pgHeading">
<h1>Terms of Use</h1>
</div>

<p>Please read this document carefully. It governs your relationship with NalliTrack.com, LLC and its affiliates (collectively, "<span style="text-decoration: underline;">NalliTrack</span>"). Set forth below are the terms and conditions under which NalliTrack makes the internet website at <a href="http://NalliTrack.com" target="_blank">NalliTrack.com</a> and its sister websites (the "<span style="text-decoration: underline;">Site</span>"), and the services available through the Site or otherwise provided by NalliTrack (the "<span style="text-decoration: underline;">Services</span>"), to each person or entity (each a "<span style="text-decoration: underline;">User</span>") accessing or using the Site or the Services.</p>
<p>These terms and conditions, together with any and all other terms, conditions, rules, policies or procedures ("<span style="text-decoration: underline;">Additional Terms</span>") published on the site from time to time and related to User's use of the Site or the Services (together, this "<span style="text-decoration: underline;">Agreement</span>"), each as updated from time to time by NalliTrack, constitute a binding, legal agreement between NalliTrack and User.</p>
<p>By using the Site or the Services (including by responding to surveys, polls or other communications received from other Users of the Site and the Services), each User hereby agrees to and is bound by this Agreement. If you do not agree with any of the terms of this Agreement, do not access or otherwise use this Site or the Services or any information contained on this Site. NalliTrack may make changes to the content and Services offered on this Site at any time.</p>
<p>NalliTrack can change the terms of this Agreement at any time (including any Additional Terms). If NalliTrack changes the terms of this Agreement, NalliTrack will post an updated set of terms and conditions of use on this Site with a change notice and NalliTrack may send registered users an email notice of the changes.</p>
<p>If any modification is unacceptable to you, you shall cease using this Site and the Services. If you do not cease using this Site and the Services, you will be conclusively deemed to have accepted the change.</p>
<p>Each User hereby warrants that if it is a corporation or other legal entity, User is validly formed and existing under the laws of its jurisdiction and has duly authorized its agent or agents to enter into this Agreement and, if an individual, User is of the age of majority in his or her place of residence.</p>
<h2>1. Subscriptions and Payment</h2>
<p><strong>1.1.</strong> If User purchases a paid subscription to the Services (a "<span style="text-decoration: underline;">Subscription</span>"), User shall pay all fees, including for any additional Services purchased by User or usage that exceeds the thresholds at the rates posted, as well as any taxes, applicable to such Subscription, as published on the Site at <a href="pricing/?utm_source=terms_of_use" target="_blank">http://NalliTrack.com/pricing/</a> from time to time. NalliTrack may change such fees at any time and in its sole discretion, provided that any such change shall become effective at the end of the then-current term of User's Subscription.</p>
<p><strong>1.2. Subscription membership in the Services is on a continuous service basis. This means that, subject to the terms of this Agreement, NalliTrack will automatically renew User's Subscription at the end of its term unless User's Subscription is canceled using the tool in User's account page on the Site at any time prior to the end of the then-current Subscription.</strong> User will be charged a renewal rate equal to the rate for the immediately preceding Subscription period, based upon the Subscription program (annual, quarterly, monthly, etc.) that User has chosen, unless NalliTrack has notified User of any new rate in advance. A cancellation of a Subscription requested by User through User's account page will become effective on the date that the then-current Subscription period expires.</p>
<p><strong>1.3.</strong> If User has elected to pay the fees referred to in <span style="text-decoration: underline;">Section 1.1</span> (Subscriptions and Payment) by credit card, User hereby warrants that the credit card information provided by User is correct, and User shall promptly notify NalliTrack of any changes to such credit card information. User acknowledges and agrees that if User's credit card payment cannot be processed for any reason, NalliTrack may suspend or cancel User's Subscription.</p>
<h2>2. Registration</h2>
<p>If User has registered for an account to use the Services, User hereby warrants that the information provided by User for the purposes of such registration is complete and accurate. User shall ensure that such information is kept up to date. Upon registering for an account, each User will receive a password and an account designation. User acknowledges and agrees that User, and not NalliTrack, is responsible for User's account and all activities occurring in connection with the use of that account, whether or not User authorizes such activities.</p>
<h2>3. Content</h2>
<p><strong>3.1.</strong> User acknowledges and agrees that:</p>
<div class="indent">
<p class="indent"><strong>(a)</strong> all survey questions, information, data, text, software, music, sound, photographs, images, video, survey responses, messages or other materials communicated or transmitted using the Site or the Services ("<span style="text-decoration: underline;">Content</span>"), whether publicly posted or privately transmitted, are the sole responsibility of the person from whom such Content originated,</p>
<p class="indent"><strong>(b)</strong> User, and not NalliTrack, is responsible for all Content that User uploads, posts, emails, distributes, communicates, transmits, or otherwise makes available using the Services or that is otherwise made available through the use of User's account (if User has one), whether or not authorized by User, and</p>
<p class="indent"><strong>(c)</strong> by using the Site and the Services, User may be exposed to Content that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, libelous, vulgar, obscene, offensive, indecent, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable.</p>
</div>
<p><strong>3.2.</strong> User further acknowledges and agrees that NalliTrack does not control the Content originating from User, respondents to User's survey, or other users of the Site or the Services, and does not guarantee the accuracy, integrity or quality of such Content. Notwithstanding the foregoing, NalliTrack may review all Content and may block, modify, terminate access to, or remove any such Content that NalliTrack considers, in its sole discretion, does not comply with any of the requirements of this Agreement but NalliTrack is not obligated to do so.</p>
<p><strong>3.3.</strong> NalliTrack reserves the right to purge Content from its databases at any time and from time to time without notice. User acknowledges and agrees that User is solely responsible for backing up any Content uploaded to the Site by User or received by User through the use of the Services. NalliTrack shall not be liable for any purging, deletion, or failure to retain any such Content.</p>
<p><strong>3.4.</strong> NalliTrack may disable User's account and your access to use the Site and/or the Services and NalliTrack may recover from User any losses, damages, costs or expenses incurred by NalliTrack resulting from or arising out of User's non-compliance with any provision of this Agreement.</p>
<h2>4. User Content</h2>
<p>In connection with User's use of the Site and the Services, and without limiting any of User's other obligations under this Agreement or applicable law, User:</p>
<div class="indent">
<p class="indent"><strong>(a)</strong> shall comply with: (i) this Agreement, including NalliTrack's anti-spam policy and all other policies as published on the Site from time to time, (ii) all applicable U.S. Federal, State, local and international laws, including the CAN-SPAM Act of 2003, and all other laws related to unsolicited commercial email messages, defamation, privacy, obscenity, intellectual property or child protective email address registries, (iii) all other rules or regulations applicable to User, including regulations promulgated by the U.S. Securities and Exchange Commission and similar regulatory authorities throughout the world, and the rules of any securities exchange, and (iv) all privacy policies or similar policies or procedures to which User may be bound that are related to User's use of the Services;</p>
<p class="indent"><strong>(b)</strong> shall not upload, post, email, distribute, communicate, transmit or otherwise make available any Content: (i) that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, libelous, vulgar, obscene, offensive, indecent, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable, (ii) that infringes any patent, trademark, trade secret, copyright, or other intellectual property right of any party, (iii) that User does not have the right to make available by reason of any law or contractual or fiduciary relationship (including inside information, and proprietary or confidential information obtained or disclosed in connection with an employment relationship or pursuant to a confidentiality agreement), or (iv) that comprises or includes any "junk mail", "spam", "chain letters", "pyramid schemes", or any similar form of solicitation;</p>
<p class="indent"><strong>(c)</strong> shall not use the Site or the Services to send surveys, polls, or other materials to minors unless User is permitted to do so under all applicable laws, or to harm minors in any way, and shall not send surveys, polls or other materials to minors that would subject NalliTrack to the Children's Online Privacy and Protection Act;</p>
<p class="indent"><strong>(d)</strong> shall not impersonate any other person or entity, including NalliTrack, or a NalliTrack official, forum leader, guide or host, or falsely state or otherwise misrepresent User's affiliation with any other person or entity;</p>
<p class="indent"><strong>(e)</strong> shall, if User uses the Services to send a survey, not mislead the recipients of that survey that User may have the ability to associate individual responses to that survey with the individual email addresses to which that survey was sent by stating that User has no such ability (unless User has requested NalliTrack to disable such feature). NalliTrack recommends that Users' surveys include the following notice (or words to similar effect), if applicable:</p>
<p class="indent"><span class="indent">"Please be advised that your responses to this survey may not be treated as anonymous by the survey sender."</span></p>
<p class="indent"><strong>(f)</strong> shall not interfere with or disrupt the Site or the Services or servers or networks connected to the Site or the Service, or disobey any requirements, procedures, policies, or regulations of networks connected to the Site or the Services;</p>
<p class="indent"><strong>(g)</strong> shall not engage in excessive usage of the Site or the Services, as determined by NalliTrack in its sole discretion, including usage that adversely affects the speed, responsiveness, or functionality of the Site, or disrupts the availability of the Site and the Services for other users;</p>
<p class="indent"><strong>(h)</strong> shall not attempt to damage, deny service to, hack, crack, reverse engineer, or otherwise interfere with the Site or the Services in any manner;</p>
<p class="indent"><strong>(i)</strong> shall not upload, post, email, distribute, communicate, transmit or otherwise make available any viruses or similar malicious software that may damage the operation of a computer, the Site, or the Services;</p>
<p class="indent"><strong>(j)</strong> shall not upload survey links to message boards or newsgroups that are not relevant to the subject matter of the survey, or that prohibit such uploading without NalliTrack's prior written consent; and</p>
<p class="indent"><strong>(k)</strong> shall not use the Site or the Services to collect, process, or otherwise handle, "Protected Health Information" (as defined in 45 C.F.R. § 160.103) without NalliTrack's prior written consent.</p>
<p>User further acknowledges and agrees that NalliTrack may cooperate with any governmental authority in connection with any investigation into User's use of the Site or the Services, including use in contravention of applicable laws, and may disclose any Content, and any other information pertaining to the User or to User's use of the Site or the Services, to such governmental authority in connection with any such investigation.</p>
</div>
<h2>5. Indemnity by User</h2>
<p>User shall indemnify, defend and hold harmless NalliTrack, its affiliates, and their respective directors, officers, employees, servants and agents from and against all claims, demands, damages, liabilities and costs (including attorneys' fees on a full indemnity basis) arising out of or in connection with:</p>
<div class="indent">
<p class="indent"><strong>(a)</strong> User's use of the Site or the Services, including User's use of or reliance on any information or materials (including survey or poll results or responses) obtained through the use of the Site or the Services,</p>
<p class="indent"><strong>(b)</strong> any other use of the Services by a third party using User's account (whether or not authorized by User),</p>
<p class="indent"><strong>(c)</strong> User's breach of this Agreement, including any of User's representations and warranties under this Agreement, or</p>
<p class="indent"><strong>(d)</strong> User's contravention of any applicable law, including the CAN-SPAM Act of 2003.</p>
</div>
<h2>6. Termination</h2>
<p><strong>6.1.</strong> This Agreement shall automatically become effective upon User's first use of the Site or the Services, and continue indefinitely until it is terminated.</p>
<p><strong>6.2.</strong> NalliTrack may cancel User's Subscription (if User has one) and terminate this Agreement immediately by notice to User in the event that User breaches any of User's representations, warranties, or obligations under this Agreement (including any of User's obligations under <span style="text-decoration: underline;">Section 3</span> (Content)) or contravenes any applicable law.</p>
<p><strong>6.3.</strong> Upon termination of this Agreement for any reason, User shall immediately cease all use of the Site and the Services, and User acknowledges and agrees that NalliTrack may, in its sole discretion, take any measures NalliTrack reasonably deems necessary or desirable to prevent further use by User of the Site or Services, including by blocking User's IP address. User further acknowledges and agrees that upon termination of this Agreement, NalliTrack shall not be obliged to retain any of User's Content (including survey or poll results or responses) or to provide the same to User, but may elect to do so in its sole discretion. Termination of this Agreement shall not entitle User to a refund of any Subscription fees previously paid by User.</p>
<p><strong>6.4.</strong> The following shall survive termination of this Agreement for any reason:</p>
<div class="indent">
<p class="indent"><strong>(a)</strong> all of User's representations, warranties and indemnities given under this Agreement;</p>
<p class="indent"><strong>(b)</strong> all disclaimers of warranties, and limitations and exclusions of liability; and</p>
<p class="indent"><strong>(c)</strong> the last sentence of <span style="text-decoration: underline;">Section 3.3</span> (Content), and each of <span style="text-decoration: underline;">Sections 5</span> (Indemnity by User), <span style="text-decoration: underline;">6</span> (Termination), <span style="text-decoration: underline;">8</span> (Limitations and Exclusions of NalliTrack's Liability) and <span style="text-decoration: underline;">9</span> (Intellectual Property Rights).</p>
</div>
<h2>7. Provisions of the Site and the Services</h2>
<p><strong>7.1.</strong> NalliTrack reserves the right at any time and from time to time to modify, suspend or discontinue, temporarily or permanently, the Services or any part thereof, or User's access thereto, and to modify, suspend or delete the Site or any part thereof, with or without notice. User acknowledges and agrees that NalliTrack shall not be liable to User or to any third party for any modification, suspension or discontinuance of the Services or any modification, suspension or deletion of the Site.</p>
<p><strong>7.2.</strong> Without limiting <span style="text-decoration: underline;">Section 7.1</span> (Provision of the Site and the Services), if User engages in excessive usage of the Site or the Services (as described in <span style="text-decoration: underline;">Section 4(g)</span> (User Conduct)), NalliTrack may take such action as it considers necessary to prevent such excessive usage and to restore the availability of the Site and the Services to other users, including by limiting or suspending User's access to the Site and the Services, or by canceling User's Subscription and terminating this Agreement.</p>
<p><strong>7.3.</strong> User acknowledges and agrees that the Site and the Services are provided "as is," "where is," "as available," and "with all faults," and that NalliTrack has no responsibility or liability for the loss or deletion of, or failure to receive, process or store any Content (including survey or poll results or responses) maintained or transmitted using the Services.</p>
<p><strong>7.4.</strong> USER ACKNOWLEDGES AND AGREES THAT THE INFORMATION, SOFTWARE, PRODUCTS AND SERVICES CONTAINED IN OR AVAILABLE THROUGH THE SITE OR THE SERVICES, INCLUDING INFORMATION, SOFTWARE, PRODUCTS AND SERVICES MADE AVAILABLE BY OTHER USERS OF THE SITE OR THE SERVICES, MAY INCLUDE INACCURACIES OR ERRORS.</p>
<p><strong>7.5.</strong> USER FURTHER ACKNOWLEDGES AND AGREES THAT USER, AND NOT NALLITRACK, IS RESPONSIBLE FOR EVALUATING THE ACCURACY, RELIABILITY, COMPLETENESS, AND USEFULNESS OF ANY INFORMATION OBTAINED THROUGH THE USE OF THE SITE OR THE SERVICES.</p>
<p><strong>7.6.</strong> NALLITRACK MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, QUALITY, OR LACK OF VIRUSES OR OTHER HARMFUL COMPONENTS OF THE SITE OR THE SERVICES, OR THE ACCURACY OF SUCH INFORMATION, SOFTWARE, PRODUCTS AND SERVICES.</p>
<p><strong>7.7.</strong> TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NalliTrack, ITS AFFILIATES, AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, SERVANTS AND AGENTS HEREBY DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, WITH REGARD TO SUCH INFORMATION, SOFTWARE, PRODUCTS OR SERVICES, INCLUDING ANY WARRANTY OF NON-INFRINGEMENT OF THIRD PARTY RIGHTS, AND THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR PURPOSE.</p>
<p><strong>7.8.</strong> If you are a User located in a country embargoed by the United States, or are on the U.S Treasury Department's list of Specially Designated Nationals, you are not permitted to purchase a Subscription or any other paid services from NalliTrack.</p>
<h2>8. LIMITATIONS AND EXCLUSIONS OF NalliTrack'S LIABILITY</h2>
<p><strong>8.1.</strong> IN NO EVENT SHALL NalliTrack, ITS AFFILIATES, OR THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, SERVANTS OR AGENTS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING DAMAGES FOR LOST PROFITS, LOSS OF USE OR DATA, OR COSTS OF COVER, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THIS AGREEMENT, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY OR ANY OTHER LEGAL THEORY, EVEN IF NALLITRACK HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, INCLUDING DAMAGES ARISING OUT OF:</p>
<div class="indent">
<p class="indent"><strong>(a)</strong> THE USE OR PERFORMANCE OF, THE DELAY IN PROVIDING, THE FAILURE TO PROVIDE, OR THE INABILITY TO USE, THE SITE OR THE SERVICES, OR</p>
<p class="indent"><strong>(b)</strong> ANY INFORMATION, SOFTWARE, PRODUCTS OR SERVICES CONTAINED IN OR AVAILABLE THROUGH THE SITE OR THE SERVICES, INCLUDING INFORMATION, SOFTWARE, PRODUCTS AND SERVICES MADE AVAILABLE BY OTHER USERS OF THE SITE OR THE SERVICES.</p>
<p>USER SPECIFICALLY AGREES THAT NALLITRACK, ITS AFFILIATES, AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, SERVANTS AND AGENTS SHALL NOT BE LIABLE FOR:</p>
<p class="indent"><strong>(c)</strong> UNAUTHORIZED ACCESS TO OR ALTERATION OF ANY TRANSMISSIONS OR DATA, ANY MATERIAL OR DATA SENT OR RECEIVED OR NOT SENT OR NOT RECEIVED, OR ANY TRANSACTIONS ENTERED INTO THROUGH THE SITE OR THE SERVICES OR IN RELIANCE UPON ANY INFORMATION OBTAINED THROUGH THE USE OF THE SITE OR THE SERVICES,</p>
<p class="indent"><strong>(d)</strong> ANY THREATENING, DEFAMATORY, OBSCENE, OFFENSIVE OR ILLEGAL CONTENT OR CONDUCT OF ANY OTHER PARTY OR ANY INFRINGEMENT OF A THIRD PARTY'S RIGHTS, INCLUDING INTELLECTUAL PROPERTY RIGHTS, OR</p>
<p class="indent"><strong>(e)</strong> ANY CONTENT SENT USING, OR INCLUDED IN, THE SITE OR THE SERVICES BY ANY THIRD PARTY.</p>
</div>
<p>IF USER IS DISSATISFIED WITH ANY PORTION OF THE SITE OR THE SERVICES, USER'S SOLE AND EXCLUSIVE REMEDY IS TO TERMINATE THIS AGREEMENT AND DISCONTINUE USING THE SITE AND THE SERVICES.</p>
<p><strong>8.2.</strong> IN THE EVENT THAT, NOTWITHSTANDING THE FOREGOING EXCLUSIONS OF LIABILITY, NalliTrack, ANY OF ITS AFFILIATES, OR ANY OF THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, SERVANTS OR AGENTS IS LIABLE TO USER FOR ANY AMOUNTS UNDER THIS AGREEMENT UNDER ANY THEORY OF RECOVERY, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, NalliTrack'S (OR SUCH AFFILIATES', DIRECTOR'S, OFFICER'S, EMPLOYEE'S, SERVANT'S OR AGENT'S, AS APPLICABLE) TOTAL LIABILITY IN RESPECT OF SUCH AMOUNTS SHALL NOT EXCEED THE GREATER OF:</p>
<div class="indent">
<p class="indent"><strong>(a)</strong> THE AMOUNT OF ONE HUNDRED DOLLARS ($100.00), AND</p>
<p class="indent"><strong>(b)</strong> THE AMOUNTS ACTUALLY RECEIVED BY NALLITRACK FROM USER UNDER THIS AGREEMENT.</p>
</div>
<p><strong>8.3.</strong> USER ACKNOWLEDGES AND AGREES THAT WITHOUT THE FOREGOING EXCLUSIONS AND LIMITATIONS OF LIABILITY, NALLITRACK WOULD NOT BE ABLE TO OFFER THE SITE OR THE SERVICES, AND THAT SUCH EXCLUSIONS AND LIMITATIONS OF LIABILITY SHALL APPLY, EVEN IF THEY WOULD CAUSE USER'S REMEDIES UNDER THIS AGREEMENT TO FAIL OF THEIR ESSENTIAL PURPOSE. Notwithstanding the foregoing, some jurisdictions do not allow the exclusion or limitation of liability for incidental or consequential damages in certain circumstances, and so the foregoing limitation and exclusions may not apply to User to that extent.</p>
<h2>9. Intellectual Property Rights</h2>
<p>The Site and the Services and all information and screens appearing on this Site, including documents, services, site design, text, graphics, logos, images and icons, as well as the arrangement thereof, are the sole property of NalliTrack.com, LLC Copyright © 2010 or its third party licensors. Except as otherwise required or limited by applicable law, any reproduction, distribution, modification, retransmission, or publication of any copyrighted material is strictly prohibited without the express written consent of the copyright owner or license. NalliTrack reserves all rights in the Site and the Services that are not expressly granted. NalliTrack is a trademark of NalliTrack.com, LLC in the United States. Other trademarks, names, and logos on this Site are the property of their respective owners. Nothing in this Agreement shall be deemed to assign or transfer to User any rights to any such intellectual property. User further acknowledges and agrees that Content made available to User through the Services may be subject to the intellectual property rights of third parties.</p>
<h2>10. Privacy Policy</h2>
<p>Your use of this Site is governed by the NalliTrack privacy policy, which is available at <a href="privacypolicy.aspx" target="_blank">http://www.NalliTrack.com/privacy</a> (the "<span style="text-decoration: underline;">Privacy Policy</span>").</p>
<h2>11. General</h2>
<p><strong>11.1.</strong> NalliTrack may provide references, frames or hyperlinks to internet websites maintained by third parties. NalliTrack does not warrant that it has reviewed such third party websites and makes no claims, representations or warranties regarding such third party websites or the contents of the same. NalliTrack is not responsible for, nor does it endorse or recommend, any products or services provided by such third parties through such third party websites or by any other means.</p>
<p><strong>11.2.</strong> User acknowledges and agrees that User, and not NalliTrack, is responsible for determining which laws may apply to User's use of the Site and the Services and assessing User's obligations under such laws.</p>
<p><strong>11.3.</strong> All notices and other communications required or permitted to be given by NalliTrack to User under this Agreement will be deemed to be properly given on the date when:</p>
<div class="indent">
<p class="indent"><strong>(a)</strong> posted on the Site,</p>
<p class="indent"><strong>(b)</strong> sent by email to the email address for User last recorded by NalliTrack, or</p>
<p class="indent"><strong>(c)</strong> sent by postal mail to the postal address for User last recorded by NalliTrack.</p>
</div>
<p>User may give notices to NalliTrack under this Agreement by email to <a href="mailto:support@NalliTrack.com">support@NalliTrack.com</a>.</p>
<p><strong>11.4.</strong> This Agreement comprises the entire agreement between NalliTrack and the User relating to the Site and the Services.</p>
<p><strong>11.5.</strong> The use of the terms "includes" and "including", and similar terms, shall be deemed not to limit what else might be included.</p>
<p><strong>11.6.</strong> This Agreement shall be governed by the laws of the State of California, without reference to its conflicts of law rules, and the parties hereby submit to the exclusive jurisdiction and venue of the courts of that State.</p>
<p><strong>11.7.</strong> User may not assign this Agreement without NalliTrack's prior written consent, which may be withheld in NalliTrack's sole discretion. NalliTrack may assign this Agreement at any time without notice to User.</p>
<p><strong>11.8.</strong> In any dispute arising out of this Agreement, the substantially prevailing party shall be entitled to payment of its reasonable attorneys' fees and costs.</p>
<p><strong>11.9.</strong> The failure by NalliTrack to enforce any right or provision of this Agreement shall not constitute a waiver of that provision or of any other provision of this Agreement.</p>
<p><strong>11.10.</strong> If any provision of this Agreement shall be determined to be invalid or unenforceable by a court, such provision shall be deemed severable and the remainder of this Agreement shall remain in full force and effect.</p>
