<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
| -------------------------------------------------------------------------
| Form Validation Rules
| -------------------------------------------------------------------------
|
*/
$config = array(
	'team/edit'	=>	array(
		array('field' => 'teamid', 'label' => 'Team ID', 'rules' => 'integer'),
		array('field' => 'orgName', 'label' => 'Organization name', 'rules' => 'required|min_length[5]'),
		array('field' => 'type', 'label' => 'Organization type', 'rules' => 'required'),
		array('field' => 'mascot', 'label' => 'Mascot', 'rules' => 'trim'),
		array('field' => 'venue', 'label' => 'Venue', 'rules' => 'trim'),
		array('field' => 'address1', 'label' => 'Address 1', 'rules' => 'trim'),
		array('field' => 'address2', 'label' => 'Address 2', 'rules' => 'trim'),
		array('field' => 'city', 'label' => 'City', 'rules' => 'trim'),
		array('field' => 'state', 'label' => 'State', 'rules' => 'required'),
		array('field' => 'zip', 'label' => 'Zip', 'rules' => 'integer|min_length[5]'),
		array('field' => 'contactName', 'label' => 'Contact Name', 'rules' => 'trim'),
		array('field' => 'contactEmail', 'label' => 'Contact Email', 'rules' => 'valid_email'),
		array('field' => 'contactPhone', 'label' => 'Contact Phone', 'rules' => 'trim'),
		array('field' => 'frmAction', 'label' => 'Action', 'rules' => 'trim')
	),
	'meet/edit' => array(
		array('field' => 'meetID', 'label' => 'Meet ID', 'rules' => 'integer'),
		array('field' => 'meetTitle', 'label' => 'Meet Title', 'rules' => 'required|min_length[5]'),
		array('field' => 'meetType', 'label' => 'Meet Type', 'rules' => 'required'),
		array('field' => 'venue', 'label' => 'Venue', 'rules' => 'trim'),
		array('field' => 'address1', 'label' => 'Address 1', 'rules' => 'trim'),
		array('field' => 'address2', 'label' => 'Address 2', 'rules' => 'trim'),
		array('field' => 'city', 'label' => 'City', 'rules' => 'trim'),
		array('field' => 'state', 'label' => 'State', 'rules' => 'required'),
		array('field' => 'zip', 'label' => 'Zip', 'rules' => 'integer|min_length[5]'),
		array('field' => 'contactName', 'label' => 'Contact Name', 'rules' => 'trim'),
		array('field' => 'contactEmail', 'label' => 'Contact Email', 'rules' => 'valid_email'),
		array('field' => 'contactPhone', 'label' => 'Contact Phone', 'rules' => 'trim'),
		array('field' => 'points1st', 'label' => 'Points for 1st place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'points2nd', 'label' => 'Points for 2nd place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'points3rd', 'label' => 'Points for 3rd place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'points4th', 'label' => 'Points for 4th place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'points5th', 'label' => 'Points for 5th place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'points6th', 'label' => 'Points for 6th place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'points7th', 'label' => 'Points for 7th place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'points8th', 'label' => 'Points for 8th place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'points9th', 'label' => 'Points for 9th place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'points10th', 'label' => 'Points for 10th place', 'rules' => 'integer|trim|greater_than[-1]|less_than[20]'),
		array('field' => 'scores', 'label' => 'Scores', 'rules' => 'trim'),
		array('field' => 'participantInfo', 'label' => 'Participant Info', 'rules' => 'trim'),
		array('field' => 'spectatorInfo', 'label' => 'Spectator Info', 'rules' => 'trim'),
		array('field' => 'published', 'label' => 'Published Flag', 'rules' => 'required'),
		array('field' => 'genderDiv1', 'label' => 'Gender', 'rules' => 'required'),
		array('field' => 'divName1', 'label' => 'Division', 'rules' => 'required'),
		array('field' => 'genderDiv2', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName2', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv3', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName3', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv4', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName4', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv5', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName5', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv6', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName6', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv7', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName7', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv8', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName8', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv9', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName9', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv10', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName10', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv11', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName11', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'genderDiv12', 'label' => 'Gender', 'rules' => 'trim'),
		array('field' => 'divName12', 'label' => 'Division', 'rules' => 'trim'),
		array('field' => 'meetDay1', 'label' => 'Day 1', 'rules' => 'required'),
		array('field' => 'startTimeTRACKDay1', 'label' => 'start time for track events for day 1', 'rules' => 'required'),
		array('field' => 'startTimeTRACKDay1_AMPM', 'label' => 'start time for track events for day 1 AM or PM', 'rules' => 'required'),
		array('field' => 'startTimeFIELDDay1', 'label' => 'start time for field events for day 1', 'rules' => 'required'),
		array('field' => 'startTimeFIELDDay1_AMPM', 'label' => 'start time for field events for day 1 AM or PM', 'rules' => 'required'),
		array('field' => 'meetDay2', 'label' => 'Day 2', 'rules' => 'required'),
		array('field' => 'startTimeTRACKDay2', 'label' => 'start time for track events for day 2', 'rules' => 'trim'),
		array('field' => 'startTimeTRACKDay2_AMPM', 'label' => 'start time for track events for day 2 AM or PM', 'rules' => 'trim'),
		array('field' => 'startTimeFIELDDay2', 'label' => 'start time for field events for day 2', 'rules' => 'trim'),
		array('field' => 'startTimeFIELDDay2_AMPM', 'label' => 'start time for field events for day 2 AM or PM', 'rules' => 'trim'),
		array('field' => 'meetDay3', 'label' => 'Day 3', 'rules' => 'required'),
		array('field' => 'startTimeTRACKDay3', 'label' => 'start time for track events for day 3', 'rules' => 'trim'),
		array('field' => 'startTimeTRACKDay3_AMPM', 'label' => 'start time for track events for day 3 AM or PM', 'rules' => 'trim'),
		array('field' => 'startTimeFIELDDay3', 'label' => 'start time for field events for day 3', 'rules' => 'trim'),
		array('field' => 'startTimeFIELDDay3_AMPM', 'label' => 'start time for field events for day 3 AM or PM', 'rules' => 'trim'),
		array('field' => 'meetDay4', 'label' => 'Day 4', 'rules' => 'required'),
		array('field' => 'startTimeTRACKDay4', 'label' => 'start time for track events for day 4', 'rules' => 'trim'),
		array('field' => 'startTimeTRACKDay4_AMPM', 'label' => 'start time for track events for day 4 AM or PM', 'rules' => 'trim'),
		array('field' => 'startTimeFIELDDay4', 'label' => 'start time for field events for day 4', 'rules' => 'trim'),
		array('field' => 'startTimeFIELDDay4_AMPM', 'label' => 'start time for field events for day 4 AM or PM', 'rules' => 'trim'),
		array('field' => 'numOfDays', 'label' => 'Number of Days', 'rules' => 'required|greater_than[0]|less_than[5]'),
		array('field' => 'numOfDivs', 'label' => 'Number of Divs', 'rules' => 'required|greater_than[0]|less_than[5]'),
		array('field' => 'orgNumOfDays', 'label' => 'Org Number of Days', 'rules' => 'required|greater_than[0]|less_than[5]'),
		array('field' => 'orgNumOfDivs', 'label' => 'Org Number of Div', 'rules' => 'required|greater_than[0]|less_than[13]'),
		array('field' => 'frmAction', 'label' => 'Action', 'rules' => 'trim')
	),
	'athlete/edit' => array(
		array('field' => 'athleteid', 'label' => 'Athlete ID', 'rules' => 'integer'),
		array('field' => 'firstName', 'label' => 'First Name', 'rules' => 'required|trim'),
		array('field' => 'lastName', 'label' => 'Last name', 'rules' => 'required|trim'),
		array('field' => 'gender', 'label' => 'Gender', 'rules' => 'required|trim'),
		array('field' => 'dob', 'label' => 'DOB', 'rules' => 'trim'),
		array('field' => 'academicYear', 'label' => 'Academic year', 'rules' => 'trim'),
		array('field' => 'contactEmail', 'label' => 'Contact email', 'rules' => 'valid_email|trim'),
		array('field' => 'contactPhone', 'label' => 'Contact phone', 'rules' => 'trim'),
		array('field' => 'alternateContact', 'label' => 'Alternate contact', 'rules' => 'trim'),
		array('field' => 'alternateEmail', 'label' => 'Alternate email', 'rules' => 'valid_email|trim'),
		array('field' => 'alternatePhone', 'label' => 'Alternate phone', 'rules' => 'trim'),
		array('field' => 'relationship', 'label' => 'Relationship', 'rules' => 'trim'),
		array('field' => 'orgNumOfDivs', 'label' => 'Org Number of Div', 'rules' => 'trim'),
		array('field' => 'published', 'label' => 'Published Flag', 'rules' => 'required'),
		array('field' => 'frmAction', 'label' => 'Action', 'rules' => 'trim')
	)
);
/* End of file form_validation.php */
/* Location: ./application/config/form_validation.php */
